# --- Deployment ---
# Manages the Pods running your application container.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr-deployment
  labels:
    app: homarr
spec:
  replicas: 1 # e.g., 2
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
      - name: homarr
        image: ghcr.io/homarr-labs/homarr:latest
        ports:
        - containerPort: 7575
          name: homarr-port
        # --- ADD THESE ENVIRONMENT VARIABLES ---
        env:
        #homarr internal encryption key
        - name: SECRET_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: homarr-secrets
              key: SECRET_ENCRYPTION_KEY
        - name: DATABASE_TYPE
          value: "postgres" # Tell Homarr to use PostgreSQL
        - name: DATABASE_HOST
          # Use the name of the PostgreSQL Service created above
          # Must be the Cluster IP 'name' defined in the yaml
          value: "postgre-clusterip-svc"
        - name: DATABASE_PORT
          value: "5432" # Standard PostgreSQL port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret # Use the same secret
              key: POSTGRES_DB
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret # Use the same secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret # Use the same secret
              key: POSTGRES_PASSWORD
        # --- END OF ADDED ENVIRONMENT VARIABLES ---
        volumeMounts:
          - name: homarr-data
            mountPath: /app/data # Homarr config/icons still need persistent storage
        resources:
           requests:
             memory: "64Mi"
             cpu: "100m"
           limits:
             memory: "512Mi"
             cpu: "1000m"
      volumes:
       - name: homarr-data
         persistentVolumeClaim:
          claimName: homarr-pvc